services:
- docker

before_install:
- docker pull purbon/kafka-topology-builder:latest
- ./travis/build-connection-props.sh > topology-builder.properties

script:
- 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./travis/build-pull.sh; fi'
- 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./travis/build-master.sh; fi'